export const ActionTypes = {
  SET_PETS: "SET_PETS",
  ADD_PET: "ADD_PET",
  SELECT_PET: "SELECT_PET",
  UPDATE_PET: "UPDATE_PET",
  DELETE_PET: "DELETE_PET",
  SEARCH_PET: "SEARCH_PET",
  FILTER_STATUS: "FILTER_STATUS",
  FILTER_BREED: "FILTER_BREED",
  SET_LIMIT: "SET_LIMIT",
};
